enum AnimalTypes {
    Lion = "🦁 Lion",
    Elephant = "🐘 Elephant",
    Bear = "🐻 Bear",
    Monkey = "🐒 Monkey",
    Dolphin = "🐬 Dolphin",
    Snake = "🐍 Snake",
    Turtle = "🐢 Turtle",
    Crocodile = "🐊 Crocodile",
    Parrot = "🐦 Parrot",
    Eagle = "🦅 Eagle",
    Macaw = "🦜 Macaw",
    Fish = "🐠 Fish",
    Trout = "🐟 Trout",
    Shark = "🦈 Shark",
    Octopus = "🐙 Octopus",
    Squid = "🦑 Squid",
    Frog = "🐸 Frog",
    Lizzard = "🦎 Lizard",
    Swan = "🦢 Swan",
    Duck = "🦆 Duck",
    Clownfish = "🤡 Clownfish",
    Tiger = "🐅 Tiger",
    Rinoceros = "🦏 Rhinoceros",
    Alligator = "🐊 Alligator",
    Cockatoo = "🦜 Cockatoo",
    Pufferfish = "🐡 Pufferfish",
    Panda = "🐻 Panda",
    Camel = "🐫 Camel",
    Toucan = "🐦 Toucan",
    Flamingo = "🦢 Flamingo",
};

export default AnimalTypes;